mode: debug
jwtSecret: 
gptSecret: 

qiniu:
  bucket: 
  accessKey: 
  secretKey: 
  ossDomain: 

httpAddress:
  host: 0.0.0.0
  port: 8000
  videoAddress: ./newclipVideo
  
# 密码均用于测试环境 不用于生产环境
mysqlMaster:
  host: newclip_mysql_master
  port: 3306
  username: root
  password: 
  database: newclip
  maxOpenConn: 100
  maxIdleConn: 10

mysqlSlave:
  host: newclip_mysql_slave
  port: 3306
  username: root
  password: 
  database: newclip
  maxOpenConn: 100
  maxIdleConn: 10

userRedis:
  host: newclip_redis
  port: 6379
  password:
  db: 0
  poolSize: 100

videoRedis:
  host: newclip_redis
  port: 6379
  password:
  db: 1
  poolSize: 100

commentRedis:
  host: newclip_redis
  port: 6379
  password:
  db: 2
  poolSize: 100

rabbitmq:
  host: newclipz_dev_rabbitmq
  port: 5672
  user: user
  password: password